openapi: 3.0.1
servers:
  - description: Index swagger
    #url local
    -url: https://localhost:8080
    #url produccion
    url: https://api.mibanco.com.co
info:
  description: Servicio de entidad ClienteCdtDigitalES.
  version: 0.0.1
  title: ClienteCdtDigitalES
  contact:
    name: MiBanco
    url: https://www.mibanco.com.co/
    email: api@mibanco.com.co
  license:
    name: GNU GPLv3
    url: ‘https://www.gnu.org/licenses/gpl-3.0.html’
tags:
  - name: Crear cliente cdt digital
    description: Crear cliente cdt digital
#----------------------------
#Endpoints del Entidad
#----------------------------
paths:
  /v1/es/cliente:
    post:
      tags:
        - Crear cliente type
      operationId: crear Cliente type
      requestBody:
        description: Crear cliente type
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ClienteType"
      responses:
        "200":
          description: Cliente type creado.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ClienteType"
        "400":
          description: "Parámetros de entrada no validos."
        "404":
          description: "No se encuentra el cliente."
    get:
      tags:
        - obtener todos los usuarios
      operationId: obtenerCliente
      description: obtener todos los usuarios
      responses:
        "200":
          description: obtener todos los usuarios.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ClienteType"
        "400":
          description: "Parámetros de entrada no validos."
#---------------------------------------------
#Se declaran los Modelos/Schemas del servicio
#---------------------------------------------
components:
  schemas:
    ClienteType:
      type: object
      properties:
        id:
          type: integer
          format: int64
        numeroCliente:
          type: integer
        tipoPersona:
          $ref: "#/components/schemas/TipoPersonaEnum"
        tipoDocumento:
          $ref: "#/components/schemas/TipoDocumentoEnum"
        numeroDocumento:
          type: integer
        fechaExpedicionDocumento:
          type: string
          format: date
        primerNombre:
          type: string
        numeroCelular:
          type: integer
        segundoNombre:
          type: string
        primerApellido:
          type: string
        segundoApellido:
          type: string
        correoElectronico:
          type: string
    TipoPersonaEnum:
      type: string
      enum:
        - 1 JURÍDICA
        - 2 NATURAL
    TipoDocumentoEnum:
      type: string
      enum:
        - CC CEDULA DE CIUDADANÍA
        - TI TARJETA DE IDENTIDAD
        - CDI CARNE DIPLOMATICO
        - CE CEDULA DE EXTRANJERÍA
        - CPA CEDULA PAISES ANDINOS
        - NIT NUMERO DE IDENTIFICACION TRIBUTARIA
        - PAS PASAPORTE
        - RCN REGISTRO CIVIL
        - RUT REGISTRO UNICO TRIBUTARIO
        - TE TERCEROS DEL EXTERIOR SIN DOMICILIO
        - RUMC ROTATIVO UTILIZACIONES MICROCREDITO